### ISSUE TITLE
update jenkins base image

### ISSUE THREAD

**Issue by dustymabe** [openshift/library#261]
The current version used is `v4.0`:

https://github.com/openshift/library/blob/56a82c1ffffb7d956a519e0a5113b02edadb479b/community/jenkins/imagestreams/jenkins-centos.json#L45-L48

which was last built two years ago. Could/should we update it with a newer version: https://quay.io/repository/openshift/origin-jenkins?tab=tags

**Comment by gabemontero** [comment]
the image reference in that file is ultimately irrelevant @dustymabe because it is ultimately overridden to be the image reference from the install payload, as the jenkins images are included in the OKD (and OCP) install payloads

that said, the jenkins team (@akram and @waveywaves ) and I have discussed in the past keeping it somewhat current in case users of the jenkins images who deploy them *outside* of OKD/OCP (i.e. use the image ref in the imagestream file as the basis for what to pull to install in their non OKD / OCP clusters)

but any changes along those lines would stem from issues / changes in https://github.com/openshift/jenkins

feel free to engage with those folks there, taking into account the items I noted above

this repo then has a periodic job that pull in updates from the various upstreams as they occur

**Comment by dustymabe** [comment]
to summarize:

- "it shouldn't matter because the images get populated during release, but if you want to get it updated you need to have the maintainers update https://github.com/openshift/jenkins/blob/master/2/release.version"

The reason I dug in this far is because the imagestreams for OKD 4.5 [are broken](https://github.com/openshift/okd/issues/167#issuecomment-695190009) so I was trying to dig in and find the source so I could get unblocked.

**Comment by gabemontero** [comment]
> to summarize:
> 
>     * "it shouldn't matter because the images get populated during release, but if you want to get it updated you need to have the maintainers update https://github.com/openshift/jenkins/blob/master/2/release.version"
> 
> 
> The reason I dug in this far is because the imagestreams for OKD 4.5 [are broken](https://github.com/openshift/okd/issues/167#issuecomment-695190009) so I was trying to dig in and find the source so I could get unblocked.

I see ... I can't speak to details aroun @vrutkovs 's comment `There is no easy fix for OKD 4.5 though, as it may break existing installations` but assuming that cannot be reconciled, there would be no machinations in this repo or https://github.com/openshift/jenkins to get past that

At most, users can manually install community imagestreams on 4.5 OKD ... in which case if you wanted the jenkins imagestreams updated, work in that repo as I previously noted.

Otherwise, and again aside from not knowing how existing installations would break per @vrutkovs , you've have to duplicate the list of commits 
at https://github.com/openshift/cluster-samples-operator/commits/release-4.6/assets/operator/okd-x86_64 on the 4.5 branch, plus the set of commits at https://github.com/openshift/release/commits/master/ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master__okd.yaml and whatever openshift/release commits those depend on to approximate what was done in 4.6

Epic/story level work IMO .... I'm sure @vrutkovs could shed more light on the work needed to have full fledged samples operator on OKD 4.5

**Comment by vrutkovs** [comment]
Agree with @gabemontero - Jenkins is included in the payload, so it shouldn't be ancient. 

In latest 4.5 its pointing to quay.io/openshift/okd-content@sha256:4d260147f803ebc165c02da94bf5b175f0c43c4af7ca109b66f838fc19641e12, which is built from https://github.com/openshift/jenkins/commits/bff850168142a6de2716bf14aa09bcfb40e5eb78
