### ISSUE TITLE
datavirt template has unresolvable datagrid image stream

### ISSUE THREAD

**Issue by mechevarria** [openshift/library#39]
In the templates for datavirt

https://github.com/openshift/library/tree/master/official/datavirt/templates

The references to **jboss-datagrid65-client-openshift:1.0** are unresolvable.  The version needs to be updated to either **1.1** or made optional

**Comment by coreydaley** [comment]
@mechevarria 
Those templates are being copied from https://github.com/jboss-openshift/application-templates/tree/ose-v1.4.5/datavirt, which still lists the 1.0 tag, it looks like the 1.4.6 tag is still in tech preview, so not sure why jboss-datagrid65-client-openshift:1.0 would be missing.  You may need to open an issue on their repo (https://github.com/jboss-openshift/application-templates) about it.

**Comment by bparees** [comment]
The issue is actually the imagestream is not importing the 1.0 tag.  The template is fine.

as @coreydaley noted, the issue really needs to be opened against the upstream repo(they own the imagestream too), but the fix is this:
https://github.com/jboss-openshift/application-templates/blob/ose-v1.4.6-tech-preview/jboss-image-streams.json#L1154-L1157

which ensures the import of the 1.0 tag when the imagestream is created.

if you grab the 1.4.6 version of the imagestreams and import them you should be able to see/resolve the 1.0 tag.
