### ISSUE TITLE
3scale APIcast image is pulled from incorrect registry

### ISSUE THREAD

**Issue by mayorova** [openshift/library#89]
When trying to deploy a 3scale APIcast instance with `AMP_RELEASE=2.1.0.GA` (the default value is not correct), I get the following:

```
Failed to pull image "apicast-gateway:2.1.0.GA": rpc error: code = Unknown desc = repository docker.io/apicast-gateway not found: does not exist or no pull access
```
Screenshot:
<img width="970" alt="openshift_3scale_apicast" src="https://user-images.githubusercontent.com/1270328/40427371-ca330724-5e9d-11e8-94ae-ba69b609bcfe.png">

Looks like the ImageStream is not being used. The image should be: [registry.access.redhat.com/3scale-amp21/apicast-gateway:1.4-2](https://github.com/openshift/library/blob/master/official/3scale/imagestreams/apicast-gateway.json#L37).

cc @maneta

**Comment by maneta** [comment]
yes look like somehow the imagestream has not been created on the cluster or the projects cannot find it. BTW I'm the person from 3scale Team which have introduced this templates on the library. Let me know if I can help you guys with something

**Comment by bparees** [comment]
@maneta the template is not correct.  your deploymentconfig is directly referencing an image (not an imagestream):

https://github.com/openshift/library/blob/master/official/3scale/templates/3scale-gateway.json#L98

here's an example of how to properly have a DC that references an image stream:

1) the image field actually doesn't matter much because it won't be used (it'll get updated by content from the imagestream), but if you want to follow established patterns: https://github.com/openshift/library/blob/master/official/eap/templates/eap64-basic-s2i.json#L234

2) you need an imagechangetrigger on your DC that references the imagestream you want the DC to be using: https://github.com/openshift/library/blob/master/official/eap/templates/eap64-basic-s2i.json#L283-L296
